name: Test credentials

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Test variables/secrets
      shell: bash
      run: |
        if [ -z "${{ secrets.BLUESKY_APP_PASSWORD }}" ]; then
          echo "BLUESKY_APP_PASSWORD is NOT set"
          exit 1
        else
          echo "BLUESKY_APP_PASSWORD is set"
        fi
        echo "BLUESKY_USERNAME=${{ secrets.BLUESKY_USERNAME }}"
